# Generated by Django 3.2.7 on 2021-09-23 07:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', cloudinary.models.CloudinaryField(default='photo.jpeg', max_length=255, verbose_name='image')),
                ('description', models.TextField(default='project description here')),
                ('link', models.URLField(default='', max_length=300)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
