# Generated by Django 3.2.7 on 2021-09-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20210923_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='author',
            new_name='username',
        ),
    ]
