# Generated by Django 3.2.7 on 2021-09-27 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_profile_project'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='profile',
    #         name='project',
    #         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratings.project'),
    #     ),
    # ]
