# Generated by Django 3.2.7 on 2021-09-27 10:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_remove_profile_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='photo.jpeg', max_length=255, verbose_name='image'),
        ),
    ]
