# Generated by Django 3.2.7 on 2021-09-27 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default='https://appname.herokuapp.com/', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratings.rating'),
        ),
    ]
