# Generated by Django 3.2.7 on 2021-09-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0011_auto_20210927_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ratings.project'),
        ),
    ]
