# Generated by Django 3.2.7 on 2021-09-27 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0012_alter_profile_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ratings.rating'),
        ),
    ]
