# Generated by Django 3.2.7 on 2021-09-27 19:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0018_alter_profile_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_updated',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.CASCADE, to='ratings.rating'),
        ),
    ]
