# Generated by Django 3.2.7 on 2021-09-27 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0019_auto_20210927_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.rating'),
        ),
    ]
